const cowsay = require('cowsay');
const fs = require('fs');

// Load your ASCII art from a file or directly as a string
const asciiArt = `
................................................................
............................................ ...................
........................................   .:...................
.....................................   ^<tLJ'..................
.................................  ..;[uZbhhQ'..................
..............................   ^I ,mhkbbbkL'..................
...........................   :]nZz :qbbbbbkL'..................
.......................  ..!|Uqkkhz :qbbbbbkL'      ............
....................   :_\`'Lhkbbbkz :qbbbbbkL ';i>!:'  .........
.................  \`i(Yqw".Lkbbbbkz :qbbbbbb0/QqdbdqL|" ........
.............    >x0dkkkm".Lkbbbbkz :qbbbbbbbhhkbbbbkh0I .......
.........   '!)l xakbbbbm".Lkbbbbkz :qbbbbbbZ?_YkbbbbdhY........
.......  "_rQdh~ rkbbbbbm".Lkbbbbkz :qbbbbbkL  >bbbbbbbd! ......
...... lXwkkkbb~ rkbbbbbm".Lkbbbbkz :qbbbbbkL' Ipbbbdbbk_ ......
...... -hbbbbbb~ rkbbbbbm".Lkbbbbkz :qbbbbbkL' Ipbbbbbbk_ ......
...... -kbbbbbk~ rkbbbbbm".Lkbbbbkz :qbbbbbkL  +bbbbbbbpI ......
...... -kbbbbbb~ rkbbbbbm".Lkbbbbkz :qbbbbbbw/(0bbbbbbhv .......
...... -hkkkkkk~ rhkkkkkw".QhkkkkhX :pkkkkkkdaakbbbkkkX" .......
...... <LCCCCCLi (QCCCCLY^.vLCCCCLj ,XJUUUUJ1[XOwwm0c?' ........
............................................   \`,,"'  ..........
...............................................    .............
................................................................
................................................................
................................................................
`.trim();

console.log(cowsay.say({
    text: asciiArt,
}));